version: '3.8'

services:
  central_server:
    container_name: central_server
    build: ./central_server
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - SOCKET_PORT=3001
      - DASHBOARD_PORT=3002
      - NODE_ENV=development
    volumes:
      - ./central_server/src:/code/src
      - ./central_server/package.json:/code/package.json
      - ./central_server/node_modules:/code/node_modules

