version: '3.8'

services:
  central_server:
    container_name: central_server
    build: ./central_server
    ports:
      - 10005:10005
      - 3003:3003
    environment:
      - SOCKET_PORT=10005
      - DASHBOARD_PORT=3003
      - NODE_ENV=development
    volumes:
      - ./central_server/src:/code/src
      - ./central_server/package.json:/code/package.json
      - ./central_server/node_modules:/code/node_modules

